site_name: Digital Citizenship
repo_url: https://github.com/teamdigitale/digital-citizenship
pages:
    - Home: index.md
    - Home (Italiano): index.it.md
    - Quick start (Italiano): onboarding.it.md
    - Resources: resources.md
theme: readthedocs
strict: true
extra_templates:
    - api/public.html
